version: '3.3' 
 
services: 
 
 mydiary-front: 
  build:
   dockerfile: Dockerfile 
  container_name: rolling-front 
  restart: always 
  ports: 
   - '3000:3000' 
  networks: 
   - rolling-fe-be 
 
networks: 
 rolling-be-db: {} 
 rolling-fe-be: {}
